<a href="https://colab.research.google.com/github/Abdulstar/Machine-Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Abdulstar/Machine-Learning.git

Cloning into 'Machine-Learning'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 1), reused 8 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 538.07 KiB | 12.51 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [4]:
import pandas as pd

file_path = '/content/Machine-Learning/Week 03/adult.csv'
df = pd.read_csv(file_path)

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income-class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [7]:
df.dtypes

age                 int64
 workclass         object
 fnlwgt             int64
 education         object
 education-num      int64
 marital-status    object
 occupation        object
 relationship      object
 race              object
 gender            object
 capital-gain       int64
 capital-loss       int64
 hours-per-week     int64
 native-country    object
 income-class      object
dtype: object

### Question 1b: What classification task(s) can be formulated from this data?

Multi Class Classification => workclass
Binary Classification => income-class

### Question 1c: What application question will this task be useful for?

Does the education has affect on income?
Will the capital gain affects the income-class>?

### Question 1d: What other attributes might be useful for this application question?

capital-gain

hours-per-week

income-class